### ISSUE TITLE
please update snapdragon dependency to 0.11.0

### ISSUE THREAD

**Issue by pravi** [micromatch/braces#13]
I'd like to use snapdragon 0.11.0 in debian but when using that version, lots of tests are failing with errors.

```
823) range expansion should expand negative ranges using steps::
     TypeError: Cannot read property 'length' of undefined
      at Compiler.mapVisit (node_modules/snapdragon/lib/compiler.js:228:31)
      at Compiler.<anonymous> (lib/compilers.js:55:19)
      at Compiler.visit (node_modules/snapdragon/lib/compiler.js:200:18)
      at Compiler.mapVisit (node_modules/snapdragon/lib/compiler.js:231:23)
      at Compiler.compile (node_modules/snapdragon/lib/compiler.js:263:12)
      at Snapdragon.compile (node_modules/snapdragon/index.js:131:24)
      at Braces.compile (lib/braces.js:87:29)
      at Braces.expand (lib/braces.js:97:15)
      at create (index.js:142:15)
      at memoize (index.js:293:13)
      at Function.braces.create (index.js:161:10)
      at braces.expand (index.js:82:17)
      at equal (test/regression-1.8.5.js:12:16)
      at Context.<anonymous> (test/regression-1.8.5.js:436:5)

```

**Comment by jonschlinkert** [comment]
I'd like to but unfortunately, this isn't going to happen unless someone does a PR for it. 

`braces` is stable, and upgrading a dependency version is not a justifiable reason to dedicate the development time and resources to completely re-write the parsers and compilers.
